export const USER_INIT = {
    "_id": {},
    "uNum": 0,
    "uNom": "",
    "uPrenom": "",
    "uMail": "",
    "uMailPro": "",
    "uPass": "",
    "uTel": "",
    "uInfosComp": "",
    "uStructure": "",
    "uProduction": "",
    "uVente": "",
    "uAdr_L1": "",
    "uAdr_L2": "",
    "uAdr_L3": "",
    "uAdr_CP": "",
    "uAdr_Ville": "",
    "uReferents": "",
    "uPhotoProfil": "",
    "uPhotos": "",
    "uActif": false,
    "uAdherent": false,
    "uCommission": false,
    "uProducteur": false,
    "uAdmin": false,
    "uDateCreat": new Date()
}